import type { User } from '@/types/user.types';
import type { Job } from '@/types/job.types';
import type { Offer } from '@/types/offer.types';
import type { Review } from '@/types/review.types';
import type { Category, Skill } from '@/types/category.types';
import type {
  Conversation,
  Message,
  Notification,
} from '@/types/message.types';

export interface DemoFlags {
  suspendedIds: string[];
  rejectedReasons: Record<string, string>;
}

export interface DemoDb {
  users: User[];
  jobs: Job[];
  offers: Offer[];
  reviews: Review[];
  categories: Category[];
  skills: Skill[];
  conversations: Conversation[];
  messages: Message[];
  notifications: Notification[];
  flags: DemoFlags;
}

const now = '2026-09-08T10:00:00Z';

const users: User[] = [
  {
    id: 'demo-admin',
    role: 'admin',
    account: {
      email: 'admin@patodo.com',
      passwordHash: 'demo',
      verified: true,
      lastLogin: now,
    },
    profile: {
      firstName: 'Equipo',
      lastName: 'PaTodo',
      bio: 'Administrador de la plataforma PaTodo',
    },
    contact: { phone: '+502 0000-0000', address: { city: 'Ciudad de Guatemala', country: 'GT' } },
    location: { type: 'Point', coordinates: [-90.5069, 14.6349] },
    stats: { rating: 5, ratingCount: 1, completedJobs: 0, cancelledJobs: 0, responseTimeMin: 0 },
    availability: {
      isOnline: true,
      serviceArea: { radiusKm: 50, center: { type: 'Point', coordinates: [-90.5069, 14.6349] } },
    },
    vehicleIds: [],
    skillIds: [],
    createdAt: '2026-01-05T09:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-client-carlos',
    role: 'client',
    account: {
      email: 'carlos@example.com',
      passwordHash: 'demo',
      verified: true,
      lastLogin: now,
    },
    profile: { firstName: 'Carlos', lastName: 'Orozco', gender: 'masculino', birthdate: '1988-04-12' },
    contact: {
      phone: '+502 5555-1234',
      address: { city: 'Ciudad de Guatemala', country: 'GT' },
    },
    location: { type: 'Point', coordinates: [-90.5069, 14.6349] },
    stats: { rating: 5, ratingCount: 2, completedJobs: 4, cancelledJobs: 1, responseTimeMin: 0 },
    availability: {
      isOnline: true,
      serviceArea: { radiusKm: 20, center: { type: 'Point', coordinates: [-90.5069, 14.6349] } },
    },
    vehicleIds: [],
    skillIds: [],
    createdAt: '2026-02-10T08:30:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-client-maria',
    role: 'client',
    account: {
      email: 'maria@example.com',
      passwordHash: 'demo',
      verified: true,
      lastLogin: now,
    },
    profile: { firstName: 'María', lastName: 'López', gender: 'femenino', birthdate: '1992-09-23' },
    contact: {
      phone: '+502 5555-9876',
      address: { city: 'Mixco', country: 'GT' },
    },
    location: { type: 'Point', coordinates: [-90.5085, 14.6319] },
    stats: { rating: 4.8, ratingCount: 1, completedJobs: 3, cancelledJobs: 0, responseTimeMin: 0 },
    availability: {
      isOnline: false,
      serviceArea: { radiusKm: 20, center: { type: 'Point', coordinates: [-90.5085, 14.6319] } },
    },
    vehicleIds: [],
    skillIds: [],
    createdAt: '2026-03-02T08:30:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-worker-juan',
    role: 'worker',
    account: {
      email: 'juan@example.com',
      passwordHash: 'demo',
      verified: true,
      lastLogin: now,
    },
    profile: {
      firstName: 'Juan',
      lastName: 'Pérez',
      bio: 'Profesional en plomería y fontanería con más de 10 años de experiencia. Trabajos garantizados.',
      gender: 'masculino',
      birthdate: '1985-01-15',
    },
    contact: {
      phone: '+502 5000-1111',
      address: { city: 'Ciudad de Guatemala', country: 'GT' },
    },
    location: { type: 'Point', coordinates: [-90.5123, 14.6299] },
    stats: { rating: 4.9, ratingCount: 27, completedJobs: 34, cancelledJobs: 1, responseTimeMin: 4 },
    availability: {
      isOnline: true,
      serviceArea: { radiusKm: 15, center: { type: 'Point', coordinates: [-90.5123, 14.6299] } },
    },
    vehicleIds: [],
    skillIds: ['demo-skill-plomeria', 'demo-skill-fontaneria'],
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-worker-pedro',
    role: 'worker',
    account: {
      email: 'pedro@example.com',
      passwordHash: 'demo',
      verified: true,
      lastLogin: now,
    },
    profile: {
      firstName: 'Pedro',
      lastName: 'Marín',
      bio: 'Mecánico especializado en llantas, baterías y reparación de motores. Atención a domicilio.',
      gender: 'masculino',
    },
    contact: {
      phone: '+502 5000-2222',
      address: { city: 'Villa Nueva', country: 'GT' },
    },
    location: { type: 'Point', coordinates: [-90.5871, 14.5257] },
    stats: { rating: 4.7, ratingCount: 41, completedJobs: 52, cancelledJobs: 2, responseTimeMin: 6 },
    availability: {
      isOnline: true,
      serviceArea: { radiusKm: 25, center: { type: 'Point', coordinates: [-90.5871, 14.5257] } },
    },
    vehicleIds: [],
    skillIds: ['demo-skill-cambio-llantas', 'demo-skill-reparacion-motor', 'demo-skill-bateria'],
    createdAt: '2026-01-18T11:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-worker-luis',
    role: 'worker',
    account: {
      email: 'luis@example.com',
      passwordHash: 'demo',
      verified: true,
      lastLogin: now,
    },
    profile: {
      firstName: 'Luis',
      lastName: 'Gómez',
      bio: 'Electricista certificado. Instalaciones residenciales y comerciales con los más altos estándares.',
      gender: 'masculino',
    },
    contact: {
      phone: '+502 5000-3333',
      address: { city: 'Zona 10, Ciudad de Guatemala', country: 'GT' },
    },
    location: { type: 'Point', coordinates: [-90.5035, 14.5995] },
    stats: { rating: 4.8, ratingCount: 19, completedJobs: 24, cancelledJobs: 0, responseTimeMin: 8 },
    availability: {
      isOnline: true,
      serviceArea: { radiusKm: 20, center: { type: 'Point', coordinates: [-90.5035, 14.5995] } },
    },
    vehicleIds: [],
    skillIds: ['demo-skill-instalacion-electrica', 'demo-skill-cableado'],
    createdAt: '2026-02-01T12:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-worker-rosa',
    role: 'worker',
    account: {
      email: 'rosa@example.com',
      passwordHash: 'demo',
      verified: false,
      lastLogin: '2026-09-06T16:00:00Z',
    },
    profile: {
      firstName: 'Rosa',
      lastName: 'Ruiz',
      bio: 'Asesoría legal para personas y empresas. Contratos, trámites y consultas.',
      gender: 'femenino',
    },
    contact: {
      phone: '+502 5000-4444',
      address: { city: 'Ciudad de Guatemala', country: 'GT' },
    },
    location: { type: 'Point', coordinates: [-90.512, 14.6401] },
    stats: { rating: 0, ratingCount: 0, completedJobs: 0, cancelledJobs: 0, responseTimeMin: 0 },
    availability: {
      isOnline: false,
      serviceArea: { radiusKm: 30, center: { type: 'Point', coordinates: [-90.512, 14.6401] } },
    },
    vehicleIds: [],
    skillIds: ['demo-skill-asesoria-legal'],
    createdAt: '2026-09-06T16:00:00Z',
    updatedAt: now,
  },
];

const categories: Category[] = [
  {
    id: 'demo-cat-mecanica',
    name: 'Mecánica',
    slug: 'mecanica',
    color: '#3b82f6',
    description: 'Reparación y mantenimiento de vehículos',
    icon: 'wrench',
    imageUrl: '',
    isActive: true,
    parentId: null,
    skillIds: [
      'demo-skill-cambio-llantas',
      'demo-skill-reparacion-motor',
      'demo-skill-bateria',
    ],
    sortOrder: 1,
    updatedAt: now,
  },
  {
    id: 'demo-cat-plomeria',
    name: 'Plomería',
    slug: 'plomeria',
    color: '#06b6d4',
    description: 'Instalación y reparación de tuberías y grifería',
    icon: 'droplets',
    imageUrl: '',
    isActive: true,
    parentId: null,
    skillIds: ['demo-skill-plomeria', 'demo-skill-fontaneria'],
    sortOrder: 2,
    updatedAt: now,
  },
  {
    id: 'demo-cat-electricidad',
    name: 'Electricidad',
    slug: 'electricidad',
    color: '#f59e0b',
    description: 'Instalaciones y reparaciones eléctricas',
    icon: 'zap',
    imageUrl: '',
    isActive: true,
    parentId: null,
    skillIds: ['demo-skill-instalacion-electrica', 'demo-skill-cableado'],
    sortOrder: 3,
    updatedAt: now,
  },
  {
    id: 'demo-cat-carpinteria',
    name: 'Carpintería',
    slug: 'carpinteria',
    color: '#f97316',
    description: 'Muebles y trabajos en madera',
    icon: 'hammer',
    imageUrl: '',
    isActive: true,
    parentId: null,
    skillIds: ['demo-skill-reparacion-muebles'],
    sortOrder: 4,
    updatedAt: now,
  },
  {
    id: 'demo-cat-pintura',
    name: 'Pintura',
    slug: 'pintura',
    color: '#ec4899',
    description: 'Pintura de interiores y exteriores',
    icon: 'paintbrush',
    imageUrl: '',
    isActive: true,
    parentId: null,
    skillIds: ['demo-skill-pintura-interior'],
    sortOrder: 5,
    updatedAt: now,
  },
  {
    id: 'demo-cat-jardineria',
    name: 'Jardinería',
    slug: 'jardineria',
    color: '#22c55e',
    description: 'Diseño y mantenimiento de jardines',
    icon: 'flower',
    imageUrl: '',
    isActive: true,
    parentId: null,
    skillIds: ['demo-skill-jardineria'],
    sortOrder: 6,
    updatedAt: now,
  },
  {
    id: 'demo-cat-limpieza',
    name: 'Limpieza',
    slug: 'limpieza',
    color: '#64748b',
    description: 'Limpieza de hogares y oficinas',
    icon: 'sparkles',
    imageUrl: '',
    isActive: true,
    parentId: null,
    skillIds: ['demo-skill-limpieza-domestica'],
    sortOrder: 7,
    updatedAt: now,
  },
  {
    id: 'demo-cat-abogado',
    name: 'Abogado',
    slug: 'abogado',
    color: '#8b5cf6',
    description: 'Asesoría y servicios legales',
    icon: 'scale',
    imageUrl: '',
    isActive: true,
    parentId: null,
    skillIds: ['demo-skill-asesoria-legal'],
    sortOrder: 8,
    updatedAt: now,
  },
];

const skills: Skill[] = [
  {
    id: 'demo-skill-cambio-llantas',
    name: 'Cambio de llantas',
    slug: 'cambio-llantas',
    categoryIds: ['demo-cat-mecanica'],
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-skill-reparacion-motor',
    name: 'Reparación de motor',
    slug: 'reparacion-motor',
    categoryIds: ['demo-cat-mecanica'],
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-skill-bateria',
    name: 'Batería',
    slug: 'bateria',
    categoryIds: ['demo-cat-mecanica'],
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-skill-plomeria',
    name: 'Plomería',
    slug: 'plomeria',
    categoryIds: ['demo-cat-plomeria'],
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-skill-fontaneria',
    name: 'Fontanería',
    slug: 'fontaneria',
    categoryIds: ['demo-cat-plomeria'],
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-skill-instalacion-electrica',
    name: 'Instalación eléctrica',
    slug: 'instalacion-electrica',
    categoryIds: ['demo-cat-electricidad'],
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-skill-cableado',
    name: 'Cableado',
    slug: 'cableado',
    categoryIds: ['demo-cat-electricidad'],
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-skill-reparacion-muebles',
    name: 'Reparación de muebles',
    slug: 'reparacion-muebles',
    categoryIds: ['demo-cat-carpinteria'],
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-skill-pintura-interior',
    name: 'Pintura interior',
    slug: 'pintura-interior',
    categoryIds: ['demo-cat-pintura'],
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-skill-jardineria',
    name: 'Jardinería',
    slug: 'jardineria',
    categoryIds: ['demo-cat-jardineria'],
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-skill-limpieza-domestica',
    name: 'Limpieza doméstica',
    slug: 'limpieza-domestica',
    categoryIds: ['demo-cat-limpieza'],
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: now,
  },
  {
    id: 'demo-skill-asesoria-legal',
    name: 'Asesoría legal',
    slug: 'asesoria-legal',
    categoryIds: ['demo-cat-abogado'],
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: now,
  },
];

const jobs: Job[] = [
  {
    id: 'demo-job-llanta',
    clientId: 'demo-client-carlos',
    details: {
      title: 'Cambio de llanta urgente',
      description:
        'Tengo una llanta ponchada del lado del conductor. Es un sedán 2021. Necesito que me ayuden en la zona 10.',
      categoryId: 'demo-cat-mecanica',
      skillIds: ['demo-skill-cambio-llantas'],
    },
    location: {
      coordinates: [-90.5069, 14.6349],
      address: 'Zona 10, Ciudad de Guatemala',
    },
    pricing: { proposedPrice: 35, currency: 'GTQ', priceType: 'fixed' },
    status: 'published',
    createdAt: '2026-09-07T18:30:00Z',
    updatedAt: '2026-09-07T18:30:00Z',
  },
  {
    id: 'demo-job-toma',
    clientId: 'demo-client-maria',
    details: {
      title: 'Instalación de toma corriente',
      description:
        'Necesito instalar 3 tomas corrientes nuevos en mi sala y pasillo. El cableado ya está en la pared.',
      categoryId: 'demo-cat-electricidad',
      skillIds: ['demo-skill-instalacion-electrica'],
    },
    location: {
      coordinates: [-90.5085, 14.6319],
      address: 'Mixco, Ciudad de Guatemala',
    },
    pricing: { proposedPrice: 150, currency: 'GTQ', priceType: 'negotiable' },
    status: 'published',
    createdAt: '2026-09-08T07:45:00Z',
    updatedAt: '2026-09-08T07:45:00Z',
  },
  {
    id: 'demo-job-fuga',
    clientId: 'demo-client-carlos',
    details: {
      title: 'Fuga de agua en la cocina',
      description:
        'Hay una fuga debajo del fregadero de la cocina. Pierde agua cuando abro la llave del agua caliente.',
      categoryId: 'demo-cat-plomeria',
      skillIds: ['demo-skill-fontaneria'],
    },
    location: {
      coordinates: [-90.5069, 14.6349],
      address: 'Zona 10, Ciudad de Guatemala',
    },
    pricing: { proposedPrice: 200, currency: 'GTQ', priceType: 'negotiable' },
    status: 'in_progress',
    scheduledFor: '2026-09-09T09:00:00Z',
    startedAt: '2026-09-08T08:00:00Z',
    createdAt: '2026-09-06T20:10:00Z',
    updatedAt: '2026-09-08T08:00:00Z',
  },
  {
    id: 'demo-job-pintura',
    clientId: 'demo-client-maria',
    details: {
      title: 'Pintar sala de estar',
      description:
        'Quiero pintar mi sala de estar de aproximadamente 20m². Color neutro, el cliente elige el tono.',
      categoryId: 'demo-cat-pintura',
      skillIds: ['demo-skill-pintura-interior'],
    },
    location: {
      coordinates: [-90.5085, 14.6319],
      address: 'Mixco, Ciudad de Guatemala',
    },
    pricing: { proposedPrice: 800, currency: 'GTQ', priceType: 'fixed' },
    status: 'completed',
    completedAt: '2026-09-05T18:00:00Z',
    createdAt: '2026-09-01T14:00:00Z',
    updatedAt: '2026-09-05T18:00:00Z',
  },
  {
    id: 'demo-job-bateria',
    clientId: 'demo-client-carlos',
    details: {
      title: 'Cambio de batería',
      description:
        'Mi carro no enciende en las mañanas. Creo que la batería ya cumplió su vida útil. Carro Toyota Corolla 2019.',
      categoryId: 'demo-cat-mecanica',
      skillIds: ['demo-skill-bateria'],
    },
    location: {
      coordinates: [-90.5069, 14.6349],
      address: 'Zona 10, Ciudad de Guatemala',
    },
    pricing: { proposedPrice: 250, currency: 'GTQ', priceType: 'negotiable' },
    status: 'pending',
    scheduledFor: '2026-09-10T11:00:00Z',
    createdAt: '2026-09-08T09:15:00Z',
    updatedAt: '2026-09-08T09:15:00Z',
  },
  {
    id: 'demo-job-puerta',
    clientId: 'demo-client-carlos',
    details: {
      title: 'Reparar puerta principal',
      description:
        'La puerta principal se traba y las bisagras están flojas. Necesito ajuste y lubricación.',
      categoryId: 'demo-cat-carpinteria',
      skillIds: ['demo-skill-reparacion-muebles'],
    },
    location: {
      coordinates: [-90.5069, 14.6349],
      address: 'Zona 10, Ciudad de Guatemala',
    },
    pricing: { proposedPrice: 120, currency: 'GTQ', priceType: 'fixed' },
    status: 'cancelled',
    cancellationReason: 'Ya no es necesario el servicio',
    cancelledAt: '2026-09-04T12:00:00Z',
    createdAt: '2026-09-03T10:00:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 'demo-job-grifo',
    clientId: 'demo-client-maria',
    details: {
      title: 'Cambio de grifo del baño',
      description:
        'Necesito cambiar el grifo del lavamanos del baño principal. El actual gotea constantemente.',
      categoryId: 'demo-cat-plomeria',
      skillIds: ['demo-skill-plomeria'],
    },
    location: {
      coordinates: [-90.5085, 14.6319],
      address: 'Mixco, Ciudad de Guatemala',
    },
    pricing: { proposedPrice: 60, currency: 'GTQ', priceType: 'fixed' },
    status: 'completed',
    completedAt: '2026-08-28T16:30:00Z',
    createdAt: '2026-08-27T09:00:00Z',
    updatedAt: '2026-08-28T16:30:00Z',
  },
];

const offers: Offer[] = [
  {
    id: 'demo-offer-o1',
    jobId: 'demo-job-llanta',
    workerId: 'demo-worker-pedro',
    workerSnapshot: {
      name: 'Pedro Marín',
      rating: 4.7,
      completedJobs: 52,
    },
    price: 45,
    estimatedTime: 25,
    message: 'Tengo gato hidráulico y la llanta de repuesto lista. Llego en 10 minutos.',
    status: 'pending',
    currency: 'GTQ',
    expiresAt: '2026-09-09T18:30:00Z',
    createdAt: '2026-09-07T19:02:00Z',
    updatedAt: '2026-09-07T19:02:00Z',
  },
  {
    id: 'demo-offer-o2',
    jobId: 'demo-job-llanta',
    workerId: 'demo-worker-luis',
    workerSnapshot: {
      name: 'Luis Gómez',
      rating: 4.8,
      completedJobs: 24,
    },
    price: 50,
    estimatedTime: 30,
    message: 'Buena tarde, puedo hacer el cambio completo y reviso la presión de las 4 llantas.',
    status: 'pending',
    currency: 'GTQ',
    expiresAt: '2026-09-09T18:30:00Z',
    createdAt: '2026-09-07T20:15:00Z',
    updatedAt: '2026-09-07T20:15:00Z',
  },
  {
    id: 'demo-offer-o3',
    jobId: 'demo-job-toma',
    workerId: 'demo-worker-luis',
    workerSnapshot: {
      name: 'Luis Gómez',
      rating: 4.8,
      completedJobs: 24,
    },
    price: 120,
    estimatedTime: 40,
    message: 'Electricista certificado. Incluyo material básico (tomas y caja).',
    status: 'pending',
    currency: 'GTQ',
    expiresAt: '2026-09-09T07:45:00Z',
    createdAt: '2026-09-08T08:20:00Z',
    updatedAt: '2026-09-08T08:20:00Z',
  },
  {
    id: 'demo-offer-o4',
    jobId: 'demo-job-fuga',
    workerId: 'demo-worker-juan',
    workerSnapshot: {
      name: 'Juan Pérez',
      rating: 4.9,
      completedJobs: 34,
    },
    price: 180,
    estimatedTime: 60,
    message: 'Puedo ir hoy mismo, llevo lo necesario para la reparación de la fuga.',
    status: 'accepted',
    currency: 'GTQ',
    expiresAt: '2026-09-07T20:10:00Z',
    createdAt: '2026-09-06T21:00:00Z',
    updatedAt: '2026-09-07T18:00:00Z',
  },
  {
    id: 'demo-offer-o5',
    jobId: 'demo-job-pintura',
    workerId: 'demo-worker-juan',
    workerSnapshot: {
      name: 'Juan Pérez',
      rating: 4.9,
      completedJobs: 34,
    },
    price: 750,
    estimatedTime: 240,
    message: 'Incluyo pintura, brochas y cinta protectora. Dos manos de acabado.',
    status: 'accepted',
    currency: 'GTQ',
    expiresAt: '2026-09-04T14:00:00Z',
    createdAt: '2026-09-01T15:30:00Z',
    updatedAt: '2026-09-02T10:00:00Z',
  },
  {
    id: 'demo-offer-o6',
    jobId: 'demo-job-grifo',
    workerId: 'demo-worker-juan',
    workerSnapshot: {
      name: 'Juan Pérez',
      rating: 4.9,
      completedJobs: 34,
    },
    price: 55,
    estimatedTime: 20,
    message: 'Te llevo un grifo de repuesto por si el tuyo no se puede reparar.',
    status: 'accepted',
    currency: 'GTQ',
    expiresAt: '2026-08-27T20:00:00Z',
    createdAt: '2026-08-27T10:00:00Z',
    updatedAt: '2026-08-27T11:00:00Z',
  },
];

const reviews: Review[] = [
  {
    id: 'demo-review-r1',
    jobId: 'demo-job-pintura',
    reviewerId: 'demo-client-maria',
    revieweeId: 'demo-worker-juan',
    rating: 5,
    comment:
      'Excelente trabajo, muy puntual y el acabado quedó perfecto. Volvería a contratarlo.',
    aspects: { quality: 5, punctuality: 5, communication: 4, value: 5 },
    isPublic: true,
    createdAt: '2026-09-05T19:00:00Z',
    updatedAt: '2026-09-05T19:00:00Z',
  },
  {
    id: 'demo-review-r2',
    jobId: 'demo-job-grifo',
    reviewerId: 'demo-client-maria',
    revieweeId: 'demo-worker-juan',
    rating: 5,
    comment: 'Rápido y eficiente. Trajo todo lo necesario y me explicó el mantenimiento.',
    aspects: { quality: 5, punctuality: 5, communication: 5, value: 5 },
    isPublic: true,
    createdAt: '2026-08-28T18:00:00Z',
    updatedAt: '2026-08-28T18:00:00Z',
  },
];

const conversations: Conversation[] = [
  {
    id: 'demo-conv-fuga',
    jobId: 'demo-job-fuga',
    participantIds: ['demo-client-carlos', 'demo-worker-juan'],
    participantsSnapshot: {
      'demo-client-carlos': { name: 'Carlos Pérez', avatarUrl: null },
      'demo-worker-juan': { name: 'Juan Martínez', avatarUrl: null },
    },
    lastMessage: {
      content: 'Puedo pasar mañana por la mañana',
      senderId: 'demo-worker-juan',
      type: 'text',
      createdAt: '2026-09-08T08:30:00Z',
    },
    unreadCount: { 'demo-client-carlos': 1 },
    isActive: true,
    createdAt: '2026-09-07T18:05:00Z',
    updatedAt: '2026-09-08T08:30:00Z',
  },
  {
    id: 'demo-conv-pintura',
    jobId: 'demo-job-pintura',
    participantIds: ['demo-client-maria', 'demo-worker-juan'],
    participantsSnapshot: {
      'demo-client-maria': { name: 'María López', avatarUrl: null },
      'demo-worker-juan': { name: 'Juan Martínez', avatarUrl: null },
    },
    lastMessage: {
      content: '¡Excelente trabajo, gracias!',
      senderId: 'demo-client-maria',
      type: 'text',
      createdAt: '2026-09-05T19:30:00Z',
    },
    unreadCount: { 'demo-worker-juan': 1 },
    isActive: true,
    createdAt: '2026-09-01T16:00:00Z',
    updatedAt: '2026-09-05T19:30:00Z',
  },
  {
    id: 'demo-conv-llanta',
    jobId: 'demo-job-llanta',
    participantIds: ['demo-client-carlos', 'demo-worker-pedro'],
    participantsSnapshot: {
      'demo-client-carlos': { name: 'Carlos Pérez', avatarUrl: null },
      'demo-worker-pedro': { name: 'Pedro Ramírez', avatarUrl: null },
    },
    lastMessage: {
      content: 'Buenas, tengo la llanta y las herramientas',
      senderId: 'demo-worker-pedro',
      type: 'text',
      createdAt: '2026-09-07T19:10:00Z',
    },
    unreadCount: { 'demo-client-carlos': 1 },
    isActive: true,
    createdAt: '2026-09-07T19:05:00Z',
    updatedAt: '2026-09-07T19:10:00Z',
  },
];

const messages: Message[] = [
  {
    id: 'demo-msg-m1',
    jobId: 'demo-job-fuga',
    conversationId: 'demo-conv-fuga',
    senderId: 'demo-client-carlos',
    receiverId: 'demo-worker-juan',
    content: 'Hola Juan, ¿cuándo puedes venir a revisar la fuga?',
    type: 'text',
    deliveredAt: '2026-09-07T18:05:00Z',
    readAt: '2026-09-07T18:10:00Z',
    createdAt: '2026-09-07T18:05:00Z',
    updatedAt: '2026-09-07T18:05:00Z',
  },
  {
    id: 'demo-msg-m2',
    jobId: 'demo-job-fuga',
    conversationId: 'demo-conv-fuga',
    senderId: 'demo-worker-juan',
    receiverId: 'demo-client-carlos',
    content: 'Puedo pasar mañana por la mañana',
    type: 'text',
    deliveredAt: '2026-09-08T08:30:00Z',
    createdAt: '2026-09-08T08:30:00Z',
    updatedAt: '2026-09-08T08:30:00Z',
  },
  {
    id: 'demo-msg-m3',
    jobId: 'demo-job-pintura',
    conversationId: 'demo-conv-pintura',
    senderId: 'demo-worker-juan',
    receiverId: 'demo-client-maria',
    content: '¡Listo! Quedó pintada la sala, ya puedes revisar el acabado',
    type: 'text',
    deliveredAt: '2026-09-05T18:10:00Z',
    readAt: '2026-09-05T19:00:00Z',
    createdAt: '2026-09-05T18:10:00Z',
    updatedAt: '2026-09-05T18:10:00Z',
  },
  {
    id: 'demo-msg-m4',
    jobId: 'demo-job-pintura',
    conversationId: 'demo-conv-pintura',
    senderId: 'demo-client-maria',
    receiverId: 'demo-worker-juan',
    content: '¡Excelente trabajo, gracias!',
    type: 'text',
    createdAt: '2026-09-05T19:30:00Z',
    updatedAt: '2026-09-05T19:30:00Z',
  },
  {
    id: 'demo-msg-m5',
    jobId: 'demo-job-llanta',
    conversationId: 'demo-conv-llanta',
    senderId: 'demo-worker-pedro',
    receiverId: 'demo-client-carlos',
    content: 'Buenas, tengo la llanta y las herramientas',
    type: 'text',
    deliveredAt: '2026-09-07T19:10:00Z',
    createdAt: '2026-09-07T19:10:00Z',
    updatedAt: '2026-09-07T19:10:00Z',
  },
];

const notifications: Notification[] = [
  {
    id: 'demo-notif-n1',
    userId: 'demo-client-carlos',
    type: 'offer',
    title: 'Nueva oferta recibida',
    body: 'Pedro Marín envió una oferta por "Cambio de llanta urgente"',
    read: false,
    data: { jobId: 'demo-job-llanta' },
    createdAt: '2026-09-07T19:02:00Z',
  },
  {
    id: 'demo-notif-n2',
    userId: 'demo-client-carlos',
    type: 'offer',
    title: 'Nueva oferta recibida',
    body: 'Luis Gómez envió una oferta por "Cambio de llanta urgente"',
    read: false,
    data: { jobId: 'demo-job-llanta' },
    createdAt: '2026-09-07T20:15:00Z',
  },
  {
    id: 'demo-notif-n3',
    userId: 'demo-worker-juan',
    type: 'job_status',
    title: 'Oferta aceptada',
    body: 'Carlos Orozco aceptó tu oferta para "Fuga de agua en la cocina"',
    read: false,
    data: { jobId: 'demo-job-fuga' },
    createdAt: '2026-09-07T18:00:00Z',
  },
];

export const seedData: DemoDb = {
  users,
  jobs,
  offers,
  reviews,
  categories,
  skills,
  conversations,
  messages,
  notifications,
  flags: {
    suspendedIds: [],
    rejectedReasons: {},
  },
};